// <auto-generated />
using System;
using AeroTrack.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroTrack.Api.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201094849_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroTrack.Api.Domain.Entities.Aircraft", b =>
                {
                    b.Property<string>("AircraftId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplianceStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AircraftId");

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("AeroTrack.Api.Domain.Entities.AuditLog", b =>
                {
                    b.Property<string>("AuditId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AircraftId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.HasIndex("AircraftId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AeroTrack.Api.Domain.Entities.MaintenanceTask", b =>
                {
                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AircraftId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("bit");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.HasIndex("AircraftId");

                    b.ToTable("MaintenanceTasks");
                });

            modelBuilder.Entity("AeroTrack.Api.Domain.Entities.ServiceEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AircraftId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("TaskId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasFilter("[TaskId] IS NOT NULL");

                    b.ToTable("ServiceEvents");
                });

            modelBuilder.Entity("AeroTrack.Api.Domain.Entities.SparePart", b =>
                {
                    b.Property<string>("PartId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("LastUpdated")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.HasKey("PartId");

                    b.ToTable("SpareParts");
                });

            modelBuilder.Entity("AeroTrack.Api.Domain.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            Password = "P@ssw0rd!",
                            Roles = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = "2",
                            Password = "P@ssw0rd!",
                            Roles = "Maintenance",
                            Username = "maint"
                        },
                        new
                        {
                            UserId = "3",
                            Password = "P@ssw0rd!",
                            Roles = "InventoryManager",
                            Username = "inv"
                        },
                        new
                        {
                            UserId = "4",
                            Password = "P@ssw0rd!",
                            Roles = "ComplianceOfficer",
                            Username = "comp"
                        });
                });

            modelBuilder.Entity("AeroTrack.Api.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("AeroTrack.Api.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("Audits")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("AeroTrack.Api.Domain.Entities.MaintenanceTask", b =>
                {
                    b.HasOne("AeroTrack.Api.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("Tasks")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("AeroTrack.Api.Domain.Entities.ServiceEvent", b =>
                {
                    b.HasOne("AeroTrack.Api.Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("ServiceHistory")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AeroTrack.Api.Domain.Entities.MaintenanceTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Aircraft");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("AeroTrack.Api.Domain.Entities.Aircraft", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("ServiceHistory");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
